controller:
  motion_law_parameters:
    max_velocity: [28, 28, 28]
    max_acceleration: [5.5, 5.5, 10]

  cascade_controllers:
  - name: "joint1"
    inner:
      Kp: 249
      Ki: 996
      Kd: 0.0
      filters_on_error_signal:
        - type: NotchFilter
          natural_frequency: 605
          zeros_damping: 0.1
          poles_damping: 0.6
    outer:
      Kp: 5.0
      Ki: 0.0
      Kd: 0.0
  - name: "joint2"
    inner:
      Kp: 168
      Ki: 756
      Kd: 0.0
      filters_on_error_signal:
        - type: NotchFilter
          natural_frequency: 660
          zeros_damping: 0.1
          poles_damping: 0.4

    outer:
      Kp: 5.0
      Ki: 0.0
      Kd: 0.0
  - name: "joint3"
    inner:
      Kp: 139
      Ki: 1390
      Kd: 0.0
      filters_on_error_signal:
        - type: NotchFilter
          natural_frequency: 900
          zeros_damping: 0.1
          poles_damping: 0.3
    outer:
      Kp: 15.0
      Ki: 0.0
      Kd: 0.0

model_parameters:
- -0.027057
- -0.000000
- 0.000000
- 0.000000
- 0.000000
- -0.000000
- -0.000000
- 0.000000
- 0.000000
- 0.000000
- -0.658796
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.651628
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.431429
- 3.416881
- 1.166374
- -0.097276
- -0.409444
- -0.244912




